/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "clavesRPC.h"

bool_t
xdr_RpcPaquete (XDR *xdrs, RpcPaquete *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->z))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_RpcTupla (XDR *xdrs, RpcTupla *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_string (xdrs, &objp->key, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->V_value2, 32,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_RpcPaquete (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_RpcClave (XDR *xdrs, RpcClave *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->key, 256))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_RpcGetResponse (XDR *xdrs, RpcGetResponse *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->V_value2, 32,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_RpcPaquete (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}
