/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <string.h>
#include "clavesRPC.h"
#include "claves.h"

bool_t
destroy_1_svc(int *result, struct svc_req *rqstp)
{
	(void) rqstp;

	*result = destroy();
	return TRUE;
}

bool_t
set_value_1_svc(RpcTupla arg1, int *result, struct svc_req *rqstp)
{
	struct Paquete p;

	(void) rqstp;

	p.x = arg1.value3.x;
	p.y = arg1.value3.y;
	p.z = arg1.value3.z;

	*result = set_value(arg1.key, arg1.value1, arg1.N_value2, arg1.V_value2, p);
	return TRUE;
}

bool_t
get_value_1_svc(RpcClave arg1, RpcGetResponse *result, struct svc_req *rqstp)
{
	char value1[256];
	int n_value2;
	float v_value2[32];
	struct Paquete p;
	int i;
	int status;

	(void) rqstp;

	memset(value1, 0, sizeof(value1));
	memset(v_value2, 0, sizeof(v_value2));
	memset(&p, 0, sizeof(p));

	status = get_value(arg1.key, value1, &n_value2, v_value2, &p);

	result->status = status;

	if (status == 0) {
		if (result->value1 != NULL) {
			free(result->value1);
			result->value1 = NULL;
		}

		result->value1 = strdup(value1);
		if (result->value1 == NULL) {
			result->status = -1;
			return TRUE;
		}

		result->N_value2 = n_value2;

		for (i = 0; i < 32; i++) {
			result->V_value2[i] = 0.0f;
		}
		for (i = 0; i < n_value2 && i < 32; i++) {
			result->V_value2[i] = v_value2[i];
		}

		result->value3.x = p.x;
		result->value3.y = p.y;
		result->value3.z = p.z;
	} else {
		if (result->value1 != NULL) {
			free(result->value1);
			result->value1 = NULL;
		}

		result->N_value2 = 0;
		for (i = 0; i < 32; i++) {
			result->V_value2[i] = 0.0f;
		}
		result->value3.x = 0;
		result->value3.y = 0;
		result->value3.z = 0.0;
	}

	return TRUE;
}

bool_t
modify_value_1_svc(RpcTupla arg1, int *result, struct svc_req *rqstp)
{
	struct Paquete p;

	(void) rqstp;

	p.x = arg1.value3.x;
	p.y = arg1.value3.y;
	p.z = arg1.value3.z;

	*result = modify_value(arg1.key, arg1.value1, arg1.N_value2, arg1.V_value2, p);
	return TRUE;
}

bool_t
delete_key_1_svc(RpcClave arg1, int *result, struct svc_req *rqstp)
{
	(void) rqstp;

	*result = delete_key(arg1.key);
	return TRUE;
}

bool_t
exist_1_svc(RpcClave arg1, int *result, struct svc_req *rqstp)
{
	(void) rqstp;

	*result = exist(arg1.key);
	return TRUE;
}

int
clavesrpc_prog_1_freeresult(SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	(void) transp;
	xdr_free(xdr_result, result);
	return 1;
}