/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CLAVESRPC_H_RPCGEN
#define _CLAVESRPC_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct RpcPaquete {
	int x;
	int y;
	int z;
};
typedef struct RpcPaquete RpcPaquete;

struct RpcTupla {
	char *key;
	char *value1;
	int N_value2;
	float V_value2[32];
	RpcPaquete value3;
};
typedef struct RpcTupla RpcTupla;

struct RpcClave {
	char *key;
};
typedef struct RpcClave RpcClave;

struct RpcGetResponse {
	int status;
	char *value1;
	int N_value2;
	float V_value2[32];
	RpcPaquete value3;
};
typedef struct RpcGetResponse RpcGetResponse;

#define CLAVESRPC_PROG 0x20000001
#define CLAVESRPC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define DESTROY 1
extern  enum clnt_stat destroy_1(int *, CLIENT *);
extern  bool_t destroy_1_svc(int *, struct svc_req *);
#define SET_VALUE 2
extern  enum clnt_stat set_value_1(RpcTupla , int *, CLIENT *);
extern  bool_t set_value_1_svc(RpcTupla , int *, struct svc_req *);
#define GET_VALUE 3
extern  enum clnt_stat get_value_1(RpcClave , RpcGetResponse *, CLIENT *);
extern  bool_t get_value_1_svc(RpcClave , RpcGetResponse *, struct svc_req *);
#define MODIFY_VALUE 4
extern  enum clnt_stat modify_value_1(RpcTupla , int *, CLIENT *);
extern  bool_t modify_value_1_svc(RpcTupla , int *, struct svc_req *);
#define DELETE_KEY 5
extern  enum clnt_stat delete_key_1(RpcClave , int *, CLIENT *);
extern  bool_t delete_key_1_svc(RpcClave , int *, struct svc_req *);
#define EXIST 6
extern  enum clnt_stat exist_1(RpcClave , int *, CLIENT *);
extern  bool_t exist_1_svc(RpcClave , int *, struct svc_req *);
extern int clavesrpc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define DESTROY 1
extern  enum clnt_stat destroy_1();
extern  bool_t destroy_1_svc();
#define SET_VALUE 2
extern  enum clnt_stat set_value_1();
extern  bool_t set_value_1_svc();
#define GET_VALUE 3
extern  enum clnt_stat get_value_1();
extern  bool_t get_value_1_svc();
#define MODIFY_VALUE 4
extern  enum clnt_stat modify_value_1();
extern  bool_t modify_value_1_svc();
#define DELETE_KEY 5
extern  enum clnt_stat delete_key_1();
extern  bool_t delete_key_1_svc();
#define EXIST 6
extern  enum clnt_stat exist_1();
extern  bool_t exist_1_svc();
extern int clavesrpc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_RpcPaquete (XDR *, RpcPaquete*);
extern  bool_t xdr_RpcTupla (XDR *, RpcTupla*);
extern  bool_t xdr_RpcClave (XDR *, RpcClave*);
extern  bool_t xdr_RpcGetResponse (XDR *, RpcGetResponse*);

#else /* K&R C */
extern bool_t xdr_RpcPaquete ();
extern bool_t xdr_RpcTupla ();
extern bool_t xdr_RpcClave ();
extern bool_t xdr_RpcGetResponse ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CLAVESRPC_H_RPCGEN */
